In [1]:
import numpy as np

In [8]:
list = [ '1' , '2', '3', '4', '5' ]
array_list = np.array(object = list)

## Assignment Question 1:

list and array_list is different because list has class 'list' while array_list has class 'numpy ndarray'.

In [10]:
list = [ '1' , '2', '3', '4', '5' ]
array_list = np.array(object = list)

In [13]:
print(type(list))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


## Assignment Question 2:


Data type of each and every element present in both the variable:

In [15]:
list = [ '1' , '2', '3', '4', '5' ]
array_list = np.array(object = list)

In [16]:
for element in list:
    print(type(element))
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


## Assignment Question 3:

In [17]:
list = [ '1' , '2', '3', '4', '5' ]
array_list = np.array(object = list_, dtype = int)

In [18]:
print(type(list))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [19]:
for element in list:
    print(type(list))
    
for element in array_list:
    print(type(array_list))

<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


## Consider  below code to answer further question:

In [20]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

## Assignment Question 4:

In [22]:
print(num_array.shape)
print(num_array.size)

(2, 3)
6


## Assignment Question 5:

In [26]:
zeros_matrix = np.zeros((3, 3))
print(zeros_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Assignment Question 6:

In [28]:
diag_matrix = np.eye(5)
print(diag_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
